### ISSUE TITLE
can't add a task with priority or assignees, get 403 forbidden

### ISSUE THREAD

**Issue by davismj** [quire-api/quire-api#30] opened 2019-10-21 15:45 UTC
![image](https://user-images.githubusercontent.com/3845823/67220761-5d0bbc80-f3f8-11e9-8d10-dcdadf298628.png)

This request works fine without priority, returns 403 forbidden with priority. 

![image](https://user-images.githubusercontent.com/3845823/67220624-1c13a800-f3f8-11e9-8ef5-bb0f3c810a3e.png)

Originally tried with just create tasks permission. Adding manage tasks permission (and regenerating the token) had no effect.

Identical result for assignees, board.

**Comment by cor3000** [comment] 2019-10-22 03:29
I had quite the opposite effect, for me posting a new task worked even after removing all permissions.
It seems like updating the Permission Scopes has no effect at all after initial app registration.

**Comment by davismj** [comment] 2019-10-22 03:35
Nice diagnosis. That might be exactly what I'm seeing. Can you post boards? It's not a documented part of the api but it seems that it is in there as adding the property returns a 403. I'd be *extremely* interested in posting a task with a boad.

**Comment by cor3000** [comment] 2019-10-22 04:39
thing is I am testing with the client_credentials flow from command line to automate administrative tasks (no permission delegation), so maybe permissions don't apply to this kind of flow.

creating a board works, via command line, for me:

```
./qa --POST /board/yyyyyyyyyyy '{"name": "test3"}' | jq

Response 200:
{
  "oid": "xxxxxxxxxx",
  "project": "yyyyyyyyyyy",
  "id": "test3-91",
  "name": "test3",
  ...
```

Update:
I also tested the authorization_code flow ... still I can create a board even with Read Only permission

![image](https://user-images.githubusercontent.com/3894309/67259784-45046d80-f4ca-11e9-9e3e-6b67d441363b.png)

**Comment by cor3000** [comment] 2019-10-22 04:56
what helped is to revoke the permissions from your user account.
Login to quire as a normal user, click the profile Icon -> My Apps and then revoke the permission for your current app. 
The issue is scheduled to be fixed with tomorrow's update.

**Comment by jimmyshiau** [comment] 2019-10-23 09:58
Hi @davismj 
We already fixed this permission issue
you can reopen this issue if the error still there

**Closed as completed by jimmyshiau** 2019-10-23 09:58 UTC
